### ISSUE TITLE
Error building SampleApp

### ISSUE THREAD

**Issue by HppZ** [anbare/NotificationsExtensions#15]
'TileContent' does not contain a definition for 'GetXml' and no extension method 'GetXml' accepting a first argument of type 'TileContent' could be found in MainPage.xaml.cs.

**Comment by hafizmdyasir** [comment]
I am having a similar error.
"The application identifier provided is invalid."

**Comment by HppZ** [comment]
May be the error is not about notifications, or try to use NotificationsExtensions.Win10 nuget package 14295.0.1 .

**Comment by andrewleader** [comment]
Hey Hafiz, can you give me more information about your project setup? "The application identifier provided is invalid" sounds like a WinRT error. Are you sending notifications from a background task?

I'll need more info to help you.

Thanks!
Andrew

(As for the original issue, which apparently I totally missed, you will only have the GetXml() method if you add the NuGet package to a UWP WinRT project, since GetXml uses the WinRT XmlDocument object which doesn't exist in non-WinRT projects. So for non-WinRT projects, you use the GetContent() method, which returns a string, which you can then create an XmlDocument from)

**Comment by hafizmdyasir** [comment]
Thank you sir,

but the problem disappeared after I used the GetXml() method. I was using it in a UWP project and it is working perfectly fine now. check out the attached screenshot of the tiles (Box O'T'Boxes).

they are all made with NotificationsExtension.

I thank you again sir, I am:

very sincerely yours

Hafiz Mohammad Yasir
