### ISSUE TITLE
ToastVisual does not allow adding image element

### ISSUE THREAD

**Issue by nguyenquyhy** [anbare/NotificationsExtensions#2]
According to the schema, we can put `<image placement="inline">` inside `<visual>`. However, that is not possible at the moment.

**Comment by andrewleader** [comment]
Hmm, there's supposed to be an InlineImages property on the ToastVisual class, but it's not showing up for some reason. I'm looking into it. Thanks for catching that!

**Comment by andrewleader** [comment]
So it turns out there's a bug in VS 2015 where IntelliSense doesn't expose the collection properties when using object initialization syntax.

There's two ways you can add inline images. You can use the cool C# feature, but IntelliSense won't tell you that InlineImages exists (type it anyways, and it'll compile)...

```
ToastVisual visual = new ToastVisual()
{
    InlineImages =
    {
        new ToastImage()
        {
            Source = new ToastImageSource("http://msn.com/image.jpg")
        }
    }
};
```

Or the classic way...

```
ToastVisual visual = new ToastVisual();
visual.InlineImages.Add(new ToastImage()
{
    Source = new ToastImageSource("http://msn.com/image.jpg")
});
```

Note that the cool C# way works with initializing StackPanel children, Grid children, etc... anything that has a collection property can be initialized using that first syntax. It's pretty neat. But I only found out now that IntelliSense doesn't properly expose those collection properties. It DOES expose it if you're referencing the project in your own solution (which is what I did, which is why from my perspective it was working fine), but when you reference the DLL, IntelliSense doesn't pick up those collection properties.
