### ISSUE TITLE
Incorrect file name in TestWeather.cs

### ISSUE THREAD

**Issue by Yuriy-Pelekh** [anbare/NotificationsExtensions#22]
In `TestWeather.cs` used background image: `Mostly Cloudy-Background.png` but there is no such file in sources... This file is in `*.jpg` format.

See:  https://github.com/WindowsNotifications/NotificationsExtensions/blob/master/Windows%2010/NotificationsExtensions.Test/TestWeather.cs#L17

**Comment by andrewleader** [comment]
Nice catch Yuriy. This ultimately doesn't have any impact since these unit tests don't actually send any tile notifications, so the existence of the images doesn't matter - these unit tests are simply verifying that the correct XML is produced.

But I changed it to jpg with commit f75634518d16e697d01aa245d65147719ccbffd0
