### ISSUE TITLE
Feature Request: Please make toast images accept byte array as source

### ISSUE THREAD

**Issue by soundprojects** [anbare/NotificationsExtensions#24]
Hi,

I am experimenting with the new Notification API's and so far they look great! However, I work with images in a byte array format a lot and it would be very nice if I could just enter the byte array's as my image source when I want to show them in a toast. For now I would first have to save the picture somewhere which creates the hassle of keeping track of all the pictures etc.

I hope this could be possible in the future

thanks

**Comment by andrewleader** [comment]
Hey! This isn't really an Extensions feature, but since I'm also on the team that owns the toast API's themselves, I'd love to talk about why you would need this feature in your app!

So, what app are you making and why do you need temporary images in the toasts? Why aren't those images saved somewhere as files already?

Just trying to understand your scenario. We understand the feature ask, but we want to understand why you're in this scenario where you need the image to only be on the toast, and not stored anywhere else.

Thanks!
Andrew

**Comment by soundprojects** [comment]
Thanks for the fast response,

I am making an app that stores data in a 'document' kind of fashion, which makes all the included images be saved as byte arrays. I then want to toast messages which have one of the included images in the toast.

 I first tried with external saved images, but then moving my document to another computer would cause me to lose all the images.

**Comment by andrewleader** [comment]
Ah, that makes sense.

Yeah, for now you'll have to just save the picture somewhere so that the toast can reference it, and then clean it up later. The logic shouldn't be too complicated - since toast notifications only persist for 7 days by default, you can just have a temp image folder, and periodically look through it and delete images that are older than 7 days, since the toast notification definitely won't be referencing the image anymore at that point.

We might consider allowing directly embedding the images in notifications, but we don't have any immediate plans.

However, thanks for explaining your scenario! It's really useful knowing who would use these features, it helps us prioritize features!

I'll close this issue since it's not a NotificationsExtensions feature, but your feedback has been received and is tracked in our notifications API backlog. Thanks!
