### ISSUE TITLE
Updated from 14332.0.1 to 14332.0.2 having some problems

### ISSUE THREAD

**Issue by vitordelucca** [anbare/NotificationsExtensions#27]
I updated from 14332.0.1 to 14332.0.2, and now I got this problem:  
![image](https://cloud.githubusercontent.com/assets/9909446/16641200/b4f62cbe-43d4-11e6-861a-b91f097da5f4.png)
When I go back to .1, it works again...

**Comment by andrewleader** [comment]
Hey Vitorgrs!

This is due to an issue with the 0.1 version of the package, which had an invalid reference. **You simply have to close and re-open your solution after upgrading to the 0.2 package.**

If you look at your project with the 0.1 version of the package, you'll notice a warning about a missing reference
![image](https://cloud.githubusercontent.com/assets/13246069/16642856/b4ad82e0-43c3-11e6-8181-b2e73fd6513f.png)

Then after you upgrade to 0.2, that previous invalid reference starts causing issues like you saw.

But once you close and re-open the solution, everything magically goes back to normal and the reference issue is fixed! Unfortunately we didn't catch this issue with the 0.1 version of the package earlier, so there's this broken upgrade experience. I'll add a note to the NuGet package's version info letting people know to close and re-open the solution. EDIT: I actually already had that warning on the upgrade notes for the NuGet package :P hopefully others will see it, or see your issue thread here!

Let me know if you still have problems!

Thanks,
Andrew
