### ISSUE TITLE
AdaptiveImage missing a Placement property

### ISSUE THREAD

**Issue by robertmclaws** [anbare/NotificationsExtensions#31]
Consider the following code from [the MSDN post](https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-create-adaptive-tiles):

```
<binding template="TileLarge" hint-textStacking="center">
  <group>
    <subgroup hint-weight="1"/>
    <subgroup hint-weight="2">
      <image src="Assets/Apps/Hipstame/hipster.jpg" hint-crop="circle"/>
    </subgroup>
    <subgroup hint-weight="1"/>
  </group>

  <text hint-style="title" hint-align="center">Hi,</text>
  <text hint-style="subtitleSubtle" hint-align="center">MasterHip</text>
</binding>
```

Based on Notifications Visualizer against RS1, it is possible to add `placement="peek"` to the image in the second subgroup. If adding that to the payload is indeed valid, then this code needs to be updated. if it's not valid, then the Notifications Visualizer app needs to be updated to throw an error if it's added to an image in a subgroup.

Thanks!

**Comment by andrewleader** [comment]
Hey!

I could have sworn that previously, peek images inside subgroups used to work in Windows... but looks like in the Anniversary Update it doesn't work.

So yep, you're right that I need to update the Visualizer to throw an error about that. Thanks for pointing that out! I'll add it to my backlog.

And our official stance on peek images inside subgroups is - "Don't do it." Peek images are supposed to be specified at the top level. Same with background images.

**Comment by robertmclaws** [comment]
Gotcha.

OT: Any chance for RS2 that your team could add the possibility of stacking Peek images? Would be nice if I could have a background image and then an image on top of it, especially in Peek mode.

It would also be kind of cool if you could have parallax scrolling / horizontal peek mode for those stacked images, similar to the old Walt Disney animation style. Could be interesting to see Live Tiles with the photos animation, but two images, and then the content slides left or right to peek new info.

**Comment by andrewleader** [comment]
Multiple (stacked) peek and background images is actually supported already! We originally didn't plan on it being supported, but a third party developer discovered that it worked :P

Unfortunately they discovered that after we had already released NotificationsExtensions, so the object model of one image per background/peek was already locked in place... I could add an "AdditionalPeekImages" property? What's your opinion on the best way to add support for multiple peek images without breaking the existing API surface?

That would be a neat animation! However it would have to be enabled via a property, since existing developers might rely on the images being fixed together (one developer uses the multiple background images to create an analog clock... one image for the minute hand, one for the hour hand). And frankly it's unlikely we would add an animation like that, we've got bigger fish to fry :)

**Comment by robertmclaws** [comment]
I think the easiest thing to do IMO would be to have a new `PeekImages` property, and rewire the internal Element output logic to use the `PeekImages` property instead of `PeekImage`. You could then rewire `PeekImage` to have the setter insert the value into the `PeekImages` backer (and check for duplicates), and put a non-breaking `Obsolete` warning on the old property. Doesn't break old code, but allows new functionality moving forward. Would be pretty simple to implement, too.

**Comment by andrewleader** [comment]
Yeah, sounds like a good plan, thanks for the advice!

**Comment by andrewleader** [comment]
Submitted version 4.3.25.0 of Notifications Visualizer (should be available in 15 hours), which now throws an error if a non-inline image is placed inside a subgroup, so marking this issue as closed.

For the `PeekImages` property array request, you can open a new issue on the new UWP Community Toolkit repo, which is the new home for NotificationsExtensions and a number of other libraries :) https://github.com/Microsoft/UWPCommunityToolkit
